### ISSUE TITLE
FDEL broken

### ISSUE THREAD

**Issue by Sevauk** [Sevauk/storeit#161] opened 2016-09-11 14:38 UTC

**Comment by kirly-af** [comment] 2016-10-07 16:39
?

**Comment by Sevauk** [comment] 2016-10-07 16:49
"?" ?

**Comment by Sevauk** [comment] 2016-10-07 16:49
FDEL was outputing some errors when I created this issue.

**Comment by kirly-af** [comment] 2016-11-15 16:49
Could not reproduce. Closing.

**Closed by kirly-af** 2016-11-15 16:49 UTC
Labels: desktop
